---
- hosts: thestias

  vars:
    settings_module: "hawk.settings.prod"

  environment:
    LANG: "fr_FR.UTF-8"
    PIPENV_VENV_IN_PROJECT: "true"
    PYENV_ROOT: "{{ pyenv }}"
    PATH: "{{ pyenv }}/bin:{{ pyenv }}/versions/{{ python_version }}/bin:{{ home }}/bin:{{ home }}/.cargo/bin:{{ root }}/.venv/bin:{{ ansible_env.PATH }}"
    DJANGO_SETTINGS_MODULE: "{{ settings_module }}"
    HAWK_CONFIG: "{{ data }}/config.toml"

  tasks:
    - name: Install the system
      import_tasks: tasks/system.yml

    - name: Install Hawk
      become_user: "{{ app_user }}"
      import_tasks: tasks/hawk.yml

    - name: Install the server
      import_tasks: tasks/server.yml
