- name: Should have a {{ app_user }} user
  become: true
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    home: "{{ home }}"
    group: "{{ app_group }}"
    comment: "Hawk"

- name: Should have the correct directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  with_items:
    - "{{ root }}"
    - "{{ home }}/bin"
    - "{{ pyenv }}"
    - "{{ data }}"
    - "{{ data_static }}"
    - "{{ data_user }}"
    - "{{ logs }}"

- name: Should have system dependencies installed
  become: true
  yum:
    name:
      - nginx
      - python3
      - python3-devel
      - libffi-devel
      - make
      - gcc
      - optipng

- name: Should have pyenv installed
  become_user: "{{ app_user }}"
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    version: master
    dest: "{{ pyenv }}"
    depth: 1
    force: yes
    recursive: yes

- name: Should have Python {{ python_version }} installed
  become_user: "{{ app_user }}"
  command: "pyenv install --skip-existing {{ python_version }}"

- name: Should have Rustup and nightly toolchains installed
  become_user: "{{ app_user }}"
  shell:
    cmd: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      rustup toolchain install nightly
      rustup target add x86_64-unknown-linux-musl --toolchain nightly
      rustup default nightly
    chdir: "{{ home }}"

- name: Should have pipenv installed
  become: true
  pip:
    name: pipenv
    executable: pip3

- name: Check latest dart-sass from GitHub Releases
  uri:
    url: https://api.github.com/repos/sass/dart-sass/releases/latest
    return_content: true
  register: sass_latest

- name: "Should have dart-sass {{ sass_latest.json.tag_name }} installed"
  loop: "{{ sass_latest.json.assets }}"
  when: "'linux-x64.tar.gz' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ home }}/bin/"
    keep_newer: yes
    extra_opts:
    - --strip=1
    - --no-anchored
    - sass
